# comment_width = 88
# condense_wildcard_suffixes = true
edition = "2024"
# format_code_in_doc_comments = true
# float_literal_trailing_zero = "IfNoPostfix"
# format_strings = true
# group_imports = "StdExternalCrate"
# hex_literal_case = "Lower"
# imports_granularity = "Module"
# imports_layout = "HorizontalVertical"
# inline_attribute_width = 88
match_block_trailing_comma = true
max_width = 88
# normalize_comments = true
# normalize_doc_attributes = true
# reorder_impl_items = true
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
# struct_lit_single_line = false
# struct_variant_width = 0
# struct_lit_width = 0
# tab_spaces = 2
# unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
# wrap_comments = true
